env = Environment()

sources = Glob("*.cpp")
object_list = env.Object(source = sources)

env.SharedLibrary(target='showstore', source=sources)
env.Append(LIBS = ['boost_system', 'boost_filesystem','boost_regex','yaml-cpp'])
env.Append(CCFLAGS = ['-Wall','-std=c++0x', '-g'])
